version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/pokedex
    ports:
      - "8000:8000"

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run prod

  test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: npm run test
