version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/pokedex
    ports:
      - "8000:8000"

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: npm run build
